Repository Andre-Jo/Jeju-Nongdi-BE, pull requests merged in 2025-07, with the labels that each got.

#5 #로그인 및 로그아웃 구현
  build.gradle
  src/main/java/com/jeju_nongdi/jeju_nongdi/JejuNongdiApplication.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/config/SecurityConfig.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/controller/AuthController.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/dto/ApiResponse.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/dto/AuthResponse.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/dto/LoginRequest.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/dto/SignupRequest.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/dto/UserResponse.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/entity/User.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/exception/EmailAlreadyExistsException.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/exception/GlobalExceptionHandler.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/exception/NicknameAlreadyExistsException.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/repository/UserRepository.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/security/JwtAuthenticationFilter.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/service/CustomUserDetailsService.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/service/UserService.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/util/JwtUtil.java
  src/main/resources/application.properties
  src/test/java/com/jeju_nongdi/jeju_nongdi/JejuNongdiApplicationTests.java
  src/test/java/com/jeju_nongdi/jeju_nongdi/config/SecurityConfigTest.java
  src/test/java/com/jeju_nongdi/jeju_nongdi/controller/AuthControllerTest.java
  src/test/java/com/jeju_nongdi/jeju_nongdi/entity/UserTest.java
  src/test/java/com/jeju_nongdi/jeju_nongdi/integration/AuthIntegrationTest.java
  src/test/java/com/jeju_nongdi/jeju_nongdi/service/UserServiceTest.java
  src/test/java/com/jeju_nongdi/jeju_nongdi/util/JwtUtilTest.java
  src/test/resources/application-test.properties
Labels: feature

#13 #security filterchain 인증된 사용자만 명시적으로 수정
  src/main/java/com/jeju_nongdi/jeju_nongdi/config/SecurityConfig.java
Labels: config

#20 # 지도 좌표 검색
  src/main/java/com/jeju_nongdi/jeju_nongdi/config/SecurityConfig.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/controller/JobPostingController.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/repository/JobPostingRepository.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/service/JobPostingService.java
Labels: feature

#22 feat: 실시간 채팅 시스템 구현 완료 #21
  build.gradle
  src/main/java/com/jeju_nongdi/jeju_nongdi/config/WebSocketChannelInterceptor.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/config/WebSocketConfig.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/controller/ChatController.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/controller/WebSocketChatController.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/dto/ApiResponse.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/dto/ChatMessageRequest.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/dto/ChatMessageResponse.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/dto/ChatRoomCreateRequest.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/dto/ChatRoomListResponse.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/dto/ChatRoomResponse.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/dto/UserResponse.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/dto/WebSocketChatMessage.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/entity/ChatMessage.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/entity/ChatRoom.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/entity/User.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/repository/ChatMessageRepository.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/repository/ChatRoomRepository.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/service/ChatService.java
Labels: feature

#24 # 빌드에러 수정
  src/main/java/com/jeju_nongdi/jeju_nongdi/config/SecurityConfig.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/config/WebSocketConfig.java
Labels: bug

#28 [Feature] AI 스마트 농업 도우미 - 일일 맞춤 꿀팁 API 개발
  build.gradle
  src/main/java/com/jeju_nongdi/jeju_nongdi/client/ai/OpenAiClient.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/client/price/PriceApiClient.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/client/price/PriceInfo.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/client/weather/WeatherApiClient.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/client/weather/WeatherInfo.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/config/WebClientConfig.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/controller/AiTipController.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/controller/ExternalApiController.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/controller/UserPreferenceController.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/dto/ai/AiTipResponseDto.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/dto/ai/DailyTipRequestDto.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/dto/ai/DailyTipSummaryDto.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/dto/ai/NotificationListDto.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/dto/ai/TodayFarmLifeDto.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/dto/ai/UserPreferenceDto.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/entity/AiTip.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/entity/CropInfo.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/entity/IdleFarmland.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/entity/UserPreference.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/repository/AiTipRepository.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/repository/CropInfoRepository.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/repository/UserPreferenceRepository.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/service/AiTipService.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/service/UserPreferenceService.java
  src/main/resources/application.properties
  src/test/java/com/jeju_nongdi/jeju_nongdi/ApiIntegrationTest.java
  src/test/java/com/jeju_nongdi/jeju_nongdi/controller/AuthControllerTest.java
  src/test/java/com/jeju_nongdi/jeju_nongdi/controller/IdleFarmlandControllerTest.java
  src/test/java/com/jeju_nongdi/jeju_nongdi/controller/JobPostingControllerTest.java
  src/test/java/com/jeju_nongdi/jeju_nongdi/controller/MentoringControllerTest.java
  src/test/java/com/jeju_nongdi/jeju_nongdi/entity/IdleFarmlandTest.java
  src/test/java/com/jeju_nongdi/jeju_nongdi/integration/JobPostingIntegrationTest.java
  src/test/java/com/jeju_nongdi/jeju_nongdi/service/IdleFarmlandServiceTest.java
  src/test/java/com/jeju_nongdi/jeju_nongdi/service/JobPostingServiceTest.java
  src/test/java/com/jeju_nongdi/jeju_nongdi/service/MentoringServiceTest.java
  src/test/java/com/jeju_nongdi/jeju_nongdi/service/UserServiceTest.java
Labels: feature, ai

#32 🐞bug/인증 없이 접근 가능한 경로 수정 #31
  src/main/java/com/jeju_nongdi/jeju_nongdi/config/SecurityConfig.java
Labels: bug, authentication

#34 🛠️Config/배포 DB 변경 및 보안 Key 관련 파일 분리
  .gitignore
  README.md
  build.gradle
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
Labels: config, secure

#36 Bug/035
  src/main/java/com/jeju_nongdi/jeju_nongdi/JejuNongdiApplication.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/client/weather/WeatherApiClient.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/client/weather/WeatherInfo.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/controller/WeatherController.java
Labels: bug

#40 Bug/037 기상 API 수정
  src/main/java/com/jeju_nongdi/jeju_nongdi/JejuNongdiApplication.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/client/weather/WeatherApiClient.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/client/weather/WeatherInfo.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/config/SecurityConfig.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/controller/AiTipController.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/controller/ExternalApiController.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/controller/WeatherController.java
  src/main/java/com/jeju_nongdi/jeju_nongdi/service/AiTipSchedulerService.java
  src/main/resources/application.properties
Labels: bug

#44 #로직수정
  src/main/java/com/jeju_nongdi/jeju_nongdi/client/weather/WeatherApiClient.java
  src/main/resources/application.properties
Labels: bug
